const express = require('express');
const router = express.Router();
require('dotenv').config();
router.use(express.json());
const { Index } = require('../controllers/indexController');
const rolRoutes = require('./rolRoutes');
const usuarioRoutes = require('./usuarioRoutes');
const severidadRoutes = require('./severidadRoutes');
const prioridadRoutes = require('./prioridadRoutes');
const carroceriaRoutes = require('./carroceriaRoutes');
const imperfeccionRoutes = require('./imperfeccionRoutes');
const reporteRoutes = require('./reporteRoutes');
const imagenRoutes = require('./imagenRoutes');
const { verificarToken } = require('../middlewares/authMiddleware');
// router.use('/', Index);
router.use('/roles', rolRoutes, verificarToken);
router.use('/severidades', severidadRoutes, verificarToken);
router.use('/prioridades', prioridadRoutes, verificarToken);
router.use('/imagenes', imagenRoutes, verificarToken);
router.use('/usuarios', usuarioRoutes, verificarToken);
router.use('/carrocerias', carroceriaRoutes, verificarToken);
router.use('/imperfecciones', imperfeccionRoutes, verificarToken);
router.use('/reportes', reporteRoutes, verificarToken);
module.exports = router;