const express = require('express');
const router = express.Router();
require('dotenv').config();
router.use(express.json());
const { Index } = require('../controllers/indexController');
const rolRoutes = require('./rolRoutes');
const usuarioRoutes = require('./usuarioRoutes');
const severidadRoutes = require('./severidadRoutes');
const prioridadRoutes = require('./prioridadRoutes');
const carroceriaRoutes = require('./carroceriaRoutes');
const imperfeccionRoutes = require('./imperfeccionRoutes');
const reporteRoutes = require('./reporteRoutes');
const imagenRoutes = require('./imagenRoutes');
const { verificarToken } = require('../middlewares/authMiddleware');
const authRoutes = require('./authRoutes');
// router.use('/', Index);
router.use('/roles', verificarToken, rolRoutes);
router.use('/severidades', verificarToken, severidadRoutes);
router.use('/prioridades', verificarToken, prioridadRoutes);
router.use('/imagenes', verificarToken, imagenRoutes);
router.use('/usuarios', verificarToken, usuarioRoutes);
router.use('/carrocerias', verificarToken, carroceriaRoutes);
router.use('/imperfecciones', verificarToken, imperfeccionRoutes);
router.use('/auth', authRoutes);
router.use('/reportes', verificarToken, reporteRoutes);
module.exports = router;